# Generated by Django 6.0.3 on 2026-04-01 09:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(max_length=60, unique=True)),
                ('billing_cycle', models.CharField(choices=[('D15', '15 Days'), ('M1', 'Monthly'), ('Y1', 'Yearly'), ('CUSTOM', 'Custom')], default='M1', max_length=10)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('price_paise', models.PositiveIntegerField()),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_paise', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'duration_days', 'price_paise'),
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('base_price_paise', models.PositiveIntegerField(default=0)),
                ('discount_applied_paise', models.PositiveIntegerField(default=0)),
                ('amount_paid_paise', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('razorpay_order_id', models.CharField(max_length=80, unique=True)),
                ('razorpay_payment_id', models.CharField(blank=True, default='', max_length=80)),
                ('razorpay_signature', models.CharField(blank=True, default='', max_length=256)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='core.subscriptionplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'status'], name='core_usersu_user_id_455378_idx'), models.Index(fields=['user', 'ends_at'], name='core_usersu_user_id_40210b_idx'), models.Index(fields=['razorpay_order_id'], name='core_usersu_razorpa_30711e_idx'), models.Index(fields=['razorpay_payment_id'], name='core_usersu_razorpa_ef5a47_idx')],
            },
        ),
    ]
