# Generated by Django 6.0.3 on 2026-04-01 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subscriptionplan_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_trial',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='FreeTrialGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_hash', models.CharField(max_length=128, unique=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('trial_starts_at', models.DateTimeField()),
                ('trial_ends_at', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='free_trial_grant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-granted_at',),
                'indexes': [models.Index(fields=['ip_hash'], name='core_freetr_ip_hash_216745_idx'), models.Index(fields=['trial_ends_at'], name='core_freetr_trial_e_d950f9_idx')],
            },
        ),
    ]
